namespace PIKATWEAKS2.Services;
using PIKATWEAKS2.Models;

public static class TweakCatalog
{
    public static IReadOnlyList<Tweak> All { get; } = new List<Tweak>
    {
        new Tweak { Id="v10-01", Name="Disable transparency", Category="Windows / UI", Description="Turns off Windows transparency effects.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Themes\Personalize"" /v EnableTransparency /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-02", Name="Disable taskbar animations", Category="Windows / UI", Description="Disables taskbar animation effects.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v TaskbarAnimations /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-03", Name="MenuShowDelay = 0", Category="Windows / UI", Description="Removes the classic menu show delay.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Control Panel\Desktop"" /v MenuShowDelay /t REG_SZ /d 0 /f" },
        new Tweak { Id="v10-04", Name="Show file extensions", Category="Windows / UI", Description="Shows known file extensions in Explorer.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v HideFileExt /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-05", Name="Open Explorer to This PC", Category="Windows / UI", Description="Makes Explorer open to This PC.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v LaunchTo /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-06", Name="Disable Aero Peek", Category="Windows / UI", Description="Disables desktop peek.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\DWM"" /v EnableAeroPeek /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-07", Name="Disable Aero Shake", Category="Windows / UI", Description="Disables Aero Shake window minimization.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v DisallowShaking /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-08", Name="Hide Widgets button", Category="Windows / UI", Description="Hides the taskbar Widgets button.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v TaskbarDa /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-09", Name="Disable recent-item tracking", Category="Windows / UI", Description="Stops Windows from tracking recent documents in the Start experience.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v Start_TrackDocs /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-10", Name="Disable lock-screen suggestions", Category="Windows / UI", Description="Disables rotating lock-screen overlay suggestions.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v RotatingLockScreenOverlayEnabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-11", Name="Disable notification toasts", Category="Windows / UI", Description="Disables Windows notification toasts.", Risk=TweakRisk.Medium, Recommended=false, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Notifications\Settings"" /v NOC_GLOBAL_SETTING_TOASTS_ENABLED /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-12", Name="Disable Start suggestions", Category="Windows / UI", Description="Disables Start content suggestions.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-338388Enabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-13", Name="Disable Spotlight features", Category="Windows / UI", Description="Disables Windows Spotlight features.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v DisableWindowsSpotlightFeatures /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-14", Name="Disable app-launch tracking", Category="Windows / UI", Description="Disables Start app launch tracking.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\Explorer\Advanced"" /v Start_TrackProgs /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-15", Name="Disable Windows tips", Category="Windows / UI", Description="Disables Windows tips content.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SubscribedContent-338389Enabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-16", Name="Disable feedback prompts", Category="Windows / UI", Description="Disables recurring Windows feedback prompts.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Siuf\Rules"" /v NumberOfSIUFInPeriod /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-17", Name="Enable Game Mode", Category="Gaming / Input", Description="Enables Windows Game Mode.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\GameBar"" /v AutoGameModeEnabled /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-18", Name="Disable Game DVR", Category="Gaming / Input", Description="Disables Game DVR recording.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\System\GameConfigStore"" /v GameDVR_Enabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-19", Name="Disable Game Bar capture", Category="Gaming / Input", Description="Disables Game Bar capture.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\GameDVR"" /v AppCaptureEnabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-20", Name="Enable HAGS", Category="Gaming / Input", Description="Sets Hardware-accelerated GPU scheduling to enabled.", Risk=TweakRisk.High, Recommended=false, Script=@"reg.exe add ""HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers"" /v HwSchMode /t REG_DWORD /d 2 /f" },
        new Tweak { Id="v10-21", Name="Disable HAGS", Category="Gaming / Input", Description="Sets Hardware-accelerated GPU scheduling to disabled.", Risk=TweakRisk.High, Recommended=false, Script=@"reg.exe add ""HKLM\SYSTEM\CurrentControlSet\Control\GraphicsDrivers"" /v HwSchMode /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-22", Name="Disable mouse acceleration", Category="Gaming / Input", Description="Disables classic Windows mouse acceleration thresholds.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Control Panel\Mouse"" /v MouseSpeed /t REG_SZ /d 0 /f
reg.exe add ""HKCU\Control Panel\Mouse"" /v MouseThreshold1 /t REG_SZ /d 0 /f
reg.exe add ""HKCU\Control Panel\Mouse"" /v MouseThreshold2 /t REG_SZ /d 0 /f" },
        new Tweak { Id="v10-23", Name="Keyboard delay 0 / speed 31", Category="Gaming / Input", Description="Sets keyboard repeat delay to 0 and speed to 31.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Control Panel\Keyboard"" /v KeyboardDelay /t REG_SZ /d 0 /f
reg.exe add ""HKCU\Control Panel\Keyboard"" /v KeyboardSpeed /t REG_SZ /d 31 /f" },
        new Tweak { Id="v10-24", Name="High Performance plan", Category="Gaming / Input", Description="Activates the Windows High Performance power plan.", Risk=TweakRisk.High, Recommended=false, Script=@"powercfg.exe /setactive SCHEME_MIN" },
        new Tweak { Id="v10-25", Name="Ultimate Performance plan", Category="Gaming / Input", Description="Creates/activates the Windows Ultimate Performance plan.", Risk=TweakRisk.High, Recommended=false, Script=@"powercfg.exe /duplicatescheme e9a42b02-d5df-448d-aa00-03f14749eb61
powercfg.exe /setactive e9a42b02-d5df-448d-aa00-03f14749eb61" },
        new Tweak { Id="v10-26", Name="Disable power throttling", Category="Gaming / Input", Description="Disables Windows power throttling policy.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SYSTEM\CurrentControlSet\Control\Power\PowerThrottling"" /v PowerThrottlingOff /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-27", Name="CPU minimum 100% AC", Category="Gaming / Input", Description="Sets AC CPU minimum processor state to 100%.", Risk=TweakRisk.High, Recommended=false, Script=@"powercfg.exe /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMIN 100
powercfg.exe /setactive SCHEME_CURRENT" },
        new Tweak { Id="v10-28", Name="CPU maximum 100% AC", Category="Gaming / Input", Description="Sets AC CPU maximum processor state to 100%.", Risk=TweakRisk.High, Recommended=false, Script=@"powercfg.exe /setacvalueindex SCHEME_CURRENT SUB_PROCESSOR PROCTHROTTLEMAX 100
powercfg.exe /setactive SCHEME_CURRENT" },
        new Tweak { Id="v10-29", Name="Disable USB selective suspend", Category="Gaming / Input", Description="Disables USB selective suspend on AC power.", Risk=TweakRisk.High, Recommended=false, Script=@"powercfg.exe /setacvalueindex SCHEME_CURRENT SUB_USB USBSELECTIVE 0
powercfg.exe /setactive SCHEME_CURRENT" },
        new Tweak { Id="v10-30", Name="Disable PCIe ASPM", Category="Gaming / Input", Description="Disables PCI Express link power management on AC power.", Risk=TweakRisk.High, Recommended=false, Script=@"powercfg.exe /setacvalueindex SCHEME_CURRENT SUB_PCIEXPRESS ASPM 0
powercfg.exe /setactive SCHEME_CURRENT" },
        new Tweak { Id="v10-31", Name="MMCSS Games priority", Category="Gaming / Input", Description="Raises multimedia scheduling values for the Games task profile.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v ""GPU Priority"" /t REG_DWORD /d 8 /f
reg.exe add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile\Tasks\Games"" /v Priority /t REG_DWORD /d 6 /f" },
        new Tweak { Id="v10-32", Name="Network throttling off", Category="Gaming / Input", Description="Disables the Multimedia Class Scheduler network throttling index.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Multimedia\SystemProfile"" /v NetworkThrottlingIndex /t REG_DWORD /d 4294967295 /f" },
        new Tweak { Id="v10-33", Name="Flush DNS", Category="Network / Maintenance", Description="Flushes the Windows DNS resolver cache.", Risk=TweakRisk.Medium, Recommended=false, Script=@"ipconfig.exe /flushdns" },
        new Tweak { Id="v10-34", Name="Reset Winsock", Category="Network / Maintenance", Description="Resets the Winsock catalog.", Risk=TweakRisk.High, Recommended=false, Script=@"netsh.exe winsock reset" },
        new Tweak { Id="v10-35", Name="Reset TCP/IP", Category="Network / Maintenance", Description="Resets the TCP/IP stack.", Risk=TweakRisk.High, Recommended=false, Script=@"netsh.exe int ip reset" },
        new Tweak { Id="v10-36", Name="Show IP configuration", Category="Network / Maintenance", Description="Displays the full IP configuration.", Risk=TweakRisk.Medium, Recommended=false, Script=@"ipconfig.exe /all" },
        new Tweak { Id="v10-37", Name="Show active power plan", Category="Network / Maintenance", Description="Displays the active power plan.", Risk=TweakRisk.Medium, Recommended=false, Script=@"powercfg.exe /getactivescheme" },
        new Tweak { Id="v10-38", Name="Component cleanup", Category="Network / Maintenance", Description="Runs DISM component store cleanup.", Risk=TweakRisk.High, Recommended=false, Script=@"DISM.exe /Online /Cleanup-Image /StartComponentCleanup" },
        new Tweak { Id="v10-39", Name="Check Windows system files", Category="Network / Maintenance", Description="Runs System File Checker.", Risk=TweakRisk.High, Recommended=false, Script=@"sfc.exe /scannow" },
        new Tweak { Id="v10-40", Name="Repair Windows image", Category="Network / Maintenance", Description="Runs DISM image health repair.", Risk=TweakRisk.High, Recommended=false, Script=@"DISM.exe /Online /Cleanup-Image /RestoreHealth" },
        new Tweak { Id="v10-41", Name="Optimize system drive", Category="Network / Maintenance", Description="Runs Windows Optimize Drives on C:.", Risk=TweakRisk.High, Recommended=false, Script=@"defrag.exe C: /O" },
        new Tweak { Id="v10-42", Name="Clear user TEMP", Category="Network / Maintenance", Description="Clears files and directories from the current user TEMP folder.", Risk=TweakRisk.Medium, Recommended=false, Script=@"del /f /s /q ""%TEMP%\*"" >nul 2>&1
for /d %%D in (""%TEMP%\*"") do rd /s /q ""%%D"" >nul 2>&1" },
        new Tweak { Id="v10-43", Name="Clear Windows Update cache", Category="Network / Maintenance", Description="Stops update services, clears the SoftwareDistribution download cache, then restarts services.", Risk=TweakRisk.High, Recommended=false, Script=@"net.exe stop wuauserv >nul 2>&1
net.exe stop bits >nul 2>&1
rd /s /q ""%SystemRoot%\SoftwareDistribution\Download"" >nul 2>&1
md ""%SystemRoot%\SoftwareDistribution\Download"" >nul 2>&1
net.exe start bits >nul 2>&1
net.exe start wuauserv >nul 2>&1" },
        new Tweak { Id="v10-44", Name="Show Windows version", Category="Network / Maintenance", Description="Displays the Windows version.", Risk=TweakRisk.Medium, Recommended=false, Script=@"ver" },
        new Tweak { Id="v10-45", Name="Show system information", Category="Network / Maintenance", Description="Displays Windows system information.", Risk=TweakRisk.Medium, Recommended=false, Script=@"systeminfo" },
        new Tweak { Id="v10-46", Name="Show GPU driver info", Category="Network / Maintenance", Description="Displays GPU name and driver information.", Risk=TweakRisk.Medium, Recommended=false, Script=@"powershell.exe -NoProfile -Command ""Get-CimInstance Win32_VideoController | Select-Object Name,DriverVersion,DriverDate""" },
        new Tweak { Id="v10-47", Name="SysMain = Manual", Category="Services / Storage / Extras", Description="Sets SysMain startup type to Manual.", Risk=TweakRisk.Low, Recommended=true, Script=@"sc.exe config SysMain start= demand" },
        new Tweak { Id="v10-48", Name="WSearch = Manual", Category="Services / Storage / Extras", Description="Sets Windows Search startup type to Manual.", Risk=TweakRisk.Low, Recommended=true, Script=@"sc.exe config WSearch start= demand" },
        new Tweak { Id="v10-49", Name="MapsBroker = Manual", Category="Services / Storage / Extras", Description="Sets Connected Devices Platform Maps service startup type to Manual.", Risk=TweakRisk.Low, Recommended=true, Script=@"sc.exe config MapsBroker start= demand" },
        new Tweak { Id="v10-50", Name="Fax = Manual", Category="Services / Storage / Extras", Description="Sets Fax service startup type to Manual.", Risk=TweakRisk.Low, Recommended=true, Script=@"sc.exe config Fax start= demand" },
        new Tweak { Id="v10-51", Name="RemoteRegistry = Disabled", Category="Services / Storage / Extras", Description="Disables Remote Registry startup.", Risk=TweakRisk.Low, Recommended=true, Script=@"sc.exe config RemoteRegistry start= disabled" },
        new Tweak { Id="v10-52", Name="RetailDemo = Disabled", Category="Services / Storage / Extras", Description="Disables Retail Demo startup.", Risk=TweakRisk.Low, Recommended=true, Script=@"sc.exe config RetailDemo start= disabled" },
        new Tweak { Id="v10-53", Name="XboxGipSvc = Manual", Category="Services / Storage / Extras", Description="Sets Xbox Accessory Management service to Manual.", Risk=TweakRisk.Low, Recommended=true, Script=@"sc.exe config XboxGipSvc start= demand" },
        new Tweak { Id="v10-54", Name="XblAuthManager = Manual", Category="Services / Storage / Extras", Description="Sets Xbox Live Auth Manager to Manual.", Risk=TweakRisk.Low, Recommended=true, Script=@"sc.exe config XblAuthManager start= demand" },
        new Tweak { Id="v10-55", Name="Disable Delivery Optimization P2P", Category="Services / Storage / Extras", Description="Sets Delivery Optimization download mode to HTTP-only.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\DeliveryOptimization"" /v DODownloadMode /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-56", Name="Enable long Win32 paths", Category="Services / Storage / Extras", Description="Enables long path support.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SYSTEM\CurrentControlSet\Control\FileSystem"" /v LongPathsEnabled /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-57", Name="Disable Search device history", Category="Services / Storage / Extras", Description="Disables device search history.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SearchSettings"" /v IsDeviceSearchHistoryEnabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-58", Name="Disable Advertising ID", Category="Services / Storage / Extras", Description="Disables the current-user advertising ID.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\AdvertisingInfo"" /v Enabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-59", Name="Disable background apps", Category="Services / Storage / Extras", Description="Disables background app access globally for the current user.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\BackgroundAccessApplications"" /v GlobalUserDisabled /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-60", Name="Disable consumer features", Category="Services / Storage / Extras", Description="Disables Windows consumer feature suggestions.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\CloudContent"" /v DisableWindowsConsumerFeatures /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-61", Name="Disable Edge Startup Boost", Category="Services / Storage / Extras", Description="Disables Microsoft Edge Startup Boost policy.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Policies\Microsoft\Edge"" /v StartupBoostEnabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-62", Name="Disable Edge Background Mode", Category="Services / Storage / Extras", Description="Disables Microsoft Edge background mode policy.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Policies\Microsoft\Edge"" /v BackgroundModeEnabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-63", Name="Disable Chrome Startup Boost", Category="Services / Storage / Extras", Description="Disables Chrome Startup Boost policy.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Policies\Google\Chrome"" /v StartupBoostEnabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-64", Name="Disable Chrome Background Mode", Category="Services / Storage / Extras", Description="Disables Chrome background mode policy.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Policies\Google\Chrome"" /v BackgroundModeEnabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-65", Name="Disable Remote Assistance", Category="Services / Storage / Extras", Description="Disables Remote Assistance.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SYSTEM\CurrentControlSet\Control\Remote Assistance"" /v fAllowToGetHelp /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-66", Name="Disable Windows Error Reporting", Category="Services / Storage / Extras", Description="Disables Windows Error Reporting policy.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting"" /v Disabled /t REG_DWORD /d 1 /f
reg.exe add ""HKLM\SOFTWARE\Policies\Microsoft\Windows\Windows Error Reporting"" /v DoReport /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-67", Name="Disable Sticky Keys popup", Category="Services / Storage / Extras", Description="Disables the Sticky Keys accessibility prompt.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Control Panel\Accessibility\StickyKeys"" /v Flags /t REG_SZ /d 506 /f" },
        new Tweak { Id="v10-68", Name="Disable Toggle Keys popup", Category="Services / Storage / Extras", Description="Disables the Toggle Keys accessibility prompt.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Control Panel\Accessibility\ToggleKeys"" /v Flags /t REG_SZ /d 58 /f" },
        new Tweak { Id="v10-69", Name="Disable OneDrive setting sync", Category="Services / Storage / Extras", Description="Disables selected Windows setting synchronization groups.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Personalization"" /v Enabled /t REG_DWORD /d 0 /f
reg.exe add ""HKCU\SOFTWARE\Microsoft\Windows\CurrentVersion\SettingSync\Groups\Windows"" /v Enabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-70", Name="Disable app diagnostics consent", Category="Services / Storage / Extras", Description="Sets app diagnostics consent to Deny.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\appDiagnostics"" /v Value /t REG_SZ /d Deny /f" },
        new Tweak { Id="v10-71", Name="Disable location consent", Category="Services / Storage / Extras", Description="Sets current-user location consent to Deny.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\CapabilityAccessManager\ConsentStore\location"" /v Value /t REG_SZ /d Deny /f" },
        new Tweak { Id="v10-72", Name="Disable online speech personalization", Category="Services / Storage / Extras", Description="Disables online speech personalization acceptance.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\SOFTWARE\Microsoft\Speech_OneCore\Settings\OnlineSpeechPrivacy"" /v HasAccepted /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-73", Name="Disable device metadata downloads", Category="Services / Storage / Extras", Description="Prevents device metadata downloads from the network.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKLM\SOFTWARE\Microsoft\Windows\CurrentVersion\Device Metadata"" /v PreventDeviceMetadataFromNetwork /t REG_DWORD /d 1 /f" },
        new Tweak { Id="v10-74", Name="Disable silent installed apps", Category="Services / Storage / Extras", Description="Disables silent app installation suggestions.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SilentInstalledAppsEnabled /t REG_DWORD /d 0 /f" },
        new Tweak { Id="v10-75", Name="Disable content suggestions", Category="Services / Storage / Extras", Description="Disables Windows content suggestion features.", Risk=TweakRisk.Low, Recommended=true, Script=@"reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SystemPaneSuggestionsEnabled /t REG_DWORD /d 0 /f
reg.exe add ""HKCU\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager"" /v SoftLandingEnabled /t REG_DWORD /d 0 /f" }
    };
}
